- data/json/items/book/maps.json
Ported from BN: [#2435](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2435) by [FlameStormer2000](https://github.com/FlameStormer2000)
> Add military helipad to military operations map

- data/mods/No_Portal_Storms/modinfo.json
Mods "Added No Portal Storms mod"
People many times asked about this, so here it is.
> Added No Portal Storms mod

- data/changelog.txt
- src/crafting.cpp
Features "Hands encumbrance no longer affects crafting speed, except when it's encumbrance from integrated armor"
Currently player has to manually take off gloves or similar hands-covering clothing/armor before crafting (and wear them once again after the crafting), which only increases keypresses. Also it differs from our other conventions, such as virtual walking in 6-tile radius during crafting, or that we don't need to take off masks and other mouth-covering clothing/armor during eating.
Only calculate decrease of crafting speed due to arms encumbrance if it's the encumbrance from integrated armor. Otherwise, presume that player character automatically takes off gloves and the like before crafting and wears them back after crafting.
Wore mittens, checked amount of time required to …
> Arms encumbrance no longer affects crafting speed, except when it's encumbrance from integrated armor

- src/mattack_actors.cpp
Bugfixes "Monsters won't shoot at vehicles they can't see"
Playtesting revealed that monsters with "shoot-at-vehicles" ability will shoot at vehicles even if they don't normally see them.
Added a check for visibility of vehicle before making said vehicle a target.
None.
Made a night. Get myself a bicycle. Debug-spawned a turret in 10 tiles away from me. Started moving on the bicycle. No shooting at me until I drove inside its night vision range.
None.
> Monsters won't shoot at vehicles they can't see

- data/changelog.txt
- src/grab.cpp
Balance "Drag much heavier vehicles"
See https://github.com/CleverRaven/Cataclysm-DDA/pull/63737.
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/63737 by @anoobindisguise.
None.
None.
> Drag much heavier vehicles

- data/json/item_category.json
- data/json/items/book/abstract.json
- data/json/loot_zones.json
- src/options.cpp
None
* Closes #26.
- Added a new `Martial arts manuals` item category and assigned all martial arts book to this category
- Added a new loot zone for this category
- Added a new point in `Item spawn scaling factor` option group
None
Got The Spirit of Aikido, examined it and checked item category. Opened game options to check that this new category is in `Item spawn scaling factor` option group. Opened zone manager to check that loot zone for this new category is available.
> Moved martial arts manuals to its own new item category

- data/json/mutations/mutations.json
- src/character.cpp
- src/debug_menu.cpp
- src/debug_menu.h
- src/mutation.cpp
- src/wish.cpp
None
Add a much more convenient way to debug bionics-related stuff.
Ported https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2507 by @olanti-p.
None.
Installed and uninstalled bionics through new menu without any issues.
None.
> Allow installing and removing bionics through debug menu

- data/changelog.txt
- src/crafting.cpp
- tests/crafting_test.cpp
Balance "Player character won't fail at crafting items from very easy or very fast recipes"
Previously there was always a chance to fail while crafting, even for recipes that it should be impossible to fail. For example, to craft washing kit, one needs only to combine washing board and a rag. Even a complete noob with 0 in all skills shouldn't fail at such a task. 
However, right now the chance to get a minor failure for this recipe for standard 8/8/8/8 character is a whopping 50%. What's worse, there is an overwhelming chance of more than 9% to completely destroy either washing board or a rag when combining them. I find this silly and unfun.
If difficulty of the recipe is 1 or lower, or time to craft is 10 seconds or less, then there is no chance to fail the craft.
None.
Get myself tons …
> Player character won't fail at crafting items from very easy or very fast recipes

- data/json/bionics.json
- data/json/itemgroups/Monsters_Animals_Lairs/harvest_cbm.json
- data/json/itemgroups/bionics.json
- data/json/items/bionics.json
- data/json/monsterdrops/zombie_military_pilot.json
- data/json/npcs/exodii/exodii_merchant_itemlist.json
- src/handle_action.cpp
Content "Helicopter pilot training CBM"
Add a way to be able to fly helicopters for characters even without the proficiency..
- Added the bionic and bionic item. Bionic cost, difficulty, and power cost are all taken from CQB bionic.
- Made bionic spawn: as a harvest of zomborgs, as a harvest of military zombie pilots, as a part of Exodii merchandise, and also as random roll for `bionics` item group.
- Added a check for this bionic into `pldrive` function.
Make a computer which will learn you to fly through some sci-fi mumbo-jumbo.
Got Apache, turned on its engines, tried to ascend. Fail.
Got this bionic, activated it, tried to ascend. Success.
None.
> Helicopter pilot training CBM

- data/json/furniture_and_terrain/furniture-domestic_plants.json
Content "Added ability to remove plants from planters without destroying planter"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64811 by @stubkan.
> Added ability to remove plants from planters without destroying planter

- src/activity_handlers.cpp
- src/game.cpp
Features "Enable auto pulping acidic zombies if acid protected"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64829 by @Rewryte.
> Enable auto pulping acidic zombies if acid protected

- src/creature.cpp
- src/game.cpp
- src/mattack_actors.cpp
- src/monmove.cpp
- src/monster.cpp
- src/options.cpp
Interface "Enable/disable showing several non-player-related messages in the log"
Currently message log is spammed by tons of potentially unneeded information, such as "monster misses other monster" or "duck flies over the fence". I am very annoyed by such message spam, so I added an option group when player can enable or disable showing of such information.
- Added 'Additional messages in the log' option group
- Added options for showing/hiding messages for
- - "You see here x items" when player steps on tile with items
- - "Monster flies over the fence"-type of messages
- - "Monster leaps!"
- - Monster struggles to stand up after being knocked down
- - Monster/NPC hits/misses/bites/lunges/claws/throws other monster/NPC
- - Monster/NPC avoids incoming projectile from other monster/NPC
- …
> Enable/disable showing several non-player-related messages in the log

- data/json/monsters/drones.json
- data/json/monsters/feral_humans.json
- data/json/monsters/robofac_robots.json
- data/json/monsters/yrax.json
- doc/MONSTER_SPECIAL_ATTACKS.md
- src/map.cpp
- src/map.h
- src/mattack_actors.cpp
None
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64801 by @maleclypse.
> "Fire at moving vehicles" mechanics tweaks

- src/game_inventory.cpp
- src/inventory_ui.cpp
- src/inventory_ui.h
Interface "Added sorting, showing&hiding pocket contents, and scrolling via mouse in inventory screens"
Add mouse support to inventory screens.
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64750 by @katemonster33.
None.
Opened inventory screen, moved items from one container to another.
> Added sorting, showing&hiding pocket contents, and scrolling via mouse in inventory screens

- src/suffer.cpp
Balance "Reverted nerfing of nyctophobia"
Nyctophobia was designed to be harsh, challenging, and unforgiving.
Reverted https://github.com/CleverRaven/Cataclysm-DDA/pull/64141.
None.
None.
None.
> Reverted nerfing of nyctophobia

- data/raw/keybindings.json
- src/input.cpp
- src/input.h
Interface "Mouse support in keybindings menu"
Add mouse support in keybindings menu
- Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64924 by @katemonster33.
- Right mouse button now closes the keybindings menu.
None.
Opened keybindings menu and checked if mouse is working ok.
None.
> Mouse support in keybindings menu

- src/map.cpp
Balance "Neutral monsters will ignore moving vehicles with visible driver until they are moving closer than 5 tiles"
* Closes #51.
Neutral monsters will ignore moving vehicles with visible driver until they are moving closer than 5 tiles.
Change tolerable distance to 3? 7?
Hostile turret: 
- sees driver - attacks driver
- doesn't see driver - attacks vehicle
Neutral turret:
- sees driver - ignores driver/vehicle if farther than 5 tiles. Attacks vehicle if closer than 5 tiles
- doesn't see driver - attacks vehicle
Friendly turret:
- sees driver - ignores driver/vehicle
- doesn't see driver - ignores driver/vehicle
None.
> Neutral monsters will ignore moving vehicles with visible driver until they are moving closer than 5 tiles

- data/changelog.txt
- src/bionics.cpp
Features "Characters with Infection Immune trait no longer need to sterilize bionics prior to installation"
Characters with Infection Immune trait are, well, immune to infections, including those which can transmit via installation of non-sterile bionics. This change feels plausible and make trait in question more valuable.
Added check for the trait in `Character::is_installable` function.
- Characters with Disease Immune should gain this advantage too? On the other hand, "disease" in this context only relates to viral diseases like common cold and flu, and I'm not sure whether we should take other viral pathogens into consideration since we don't simulate them.
- Permit installing not only non-sterile bionics, but also filthy ones?
Got Infection Immune trait. Got non-sterile bionic. …
> Characters with Infection Immune trait no longer need to sterilize bionics prior to installation

- src/character.cpp
- src/character.h
- src/character_body.cpp
- src/monster.cpp
- src/player_hardcoded_effects.cpp
None
Resolve possible performance issues.
Applied @LazyWizard's [suggestion](https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/66#issuecomment-1522721352) and made checks for getting sick only roll when NPC or feral with `fake_common_cold` effect coughs.
Also, while I'm here, I slightly buffed environmental factor when determining player's chance to get sick as I felt that wearing no mouth protection at all and wearing a gas mask has almost the same effect when calculating this chance. 
None.
Built a cage for me and NPC with the effect. Waited for NPC to cough on me. 
None.
> Try to infect player only on feral/NPC cough

- src/trapfunc.cpp
Bugfixes "Fix temple anti-softlock code"
The colored walls segment of a strange temple is coded to let the player escape if they trap themselves, but it can fail if the player is next to the edge of the room. 
This is clearly not meant to happen.
Removes all non-colored walls from the list of toggle candidates.
I editing the map to only have 1 colored wall next to the floor and it worked 5 times in a row.
> Fix temple anti-softlock code

- src/newcharacter.cpp
Interface "Detailed information for stats on character creation menu"
More info allows less experienced players to meaningfully choose stats when creating their characters.
Looked through the code, checked for `get_str`, `dex_cur`, `EFFECT_INT` and similar and added relevant information to character creation menu.
None.
Started creating character, switched to STATS tab, looked on the screen.
> Detailed information for stats on character creation menu

- data/changelog.txt
- src/npc.h
- src/npcmove.cpp
- src/npctalk.cpp
Features "Added a NPC chat command that orders NPC to move to location player-chosen location"
More control over NPC followers.
- Added command to move NPC to player-chosen location. 
- This works only if NPC is following the player. NPCs on guard are not available for this command. 
- After NPC reaches said location, he returns to his old duties (returns to player).
- Works both for single NPC and several NPCs. 
- NPCs won't go into impassable locations.
None.
Got two friendly NPCs, made them go to location, both single and in group.
> Added a NPC chat command that orders NPC to move to location player-chosen location

- doc/JSON_FLAGS.md
- src/game.cpp
- src/monexamine.cpp
- src/monstergenerator.cpp
- src/mtype.h
- src/npctalk.cpp
- src/ui.cpp
Features "Allow conversation with monsters and show NPC location when chatting"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64928 by @Ramza13. Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/65432 by @Qrox.
> Allow conversation with monsters and show NPC location when chatting

- src/character.cpp
- src/game.cpp
- src/monmove.cpp
- src/teleport.cpp
Bugfixes "Activate trap on force-moved enemies"
Ported https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2696 by @MrLostman.
> Activate trap on force-moved enemies

- data/changelog.txt
- data/raw/keybindings.json
- src/options.cpp
- src/player_display.cpp
Interface "Larger and reorganized player info menu"
Player info menu (@ by default) was designed for outdated 80x24 terminal size and as such has several issues with our current situation.
- Encumbrance and warmth panel has space only for 9 body parts while there's 10 body parts to display. This leads to necessity of scrolling through the panel.
- Speed panel has space only for 7 effects, so if there's more than that, 8th and others ain't displayed at all. For example, there's 8th `Webbed` effect which isn't displayed in Speed panel.
- Lots of simultaneous mutations and bionics (and also effects and proficiencies) leads to necessity of scrolling through the panels as there's too small space for them.
- Overall the old layout with its 80x24 limit is hostile towards non-English languages …
> Larger and reorganized player info menu

- src/character.cpp
Bugfixes "Mounts don't fear hallucinations no more"
Mounts shouldn't fear player's hallucinations.
Added check for hallucination monsters in `check_mount_is_spooked` and also in `check_mount_will_move` functions. Also added a message indicating that the mount was actually spooked.
None.
Debug-spawned a horse, a cattle fodder, a tack, and a saddle. Feed the horse with the fodder. Mounted the horse. Debug-spawned hallucination skeletal juggernaut. Moved around the juggernaut. No forced dismount.
Debug-spawned real juggernaut. Moved around it. After some time my horse got spooked and threw me to the ground.
None.
> Mounts don't fear hallucinations no more

- src/player_display.cpp
Interface "Several tweaks to player info menu"
Make player info look prettier with large-than-default column width.
Made all values in most panels right-aligned.
None.
Opened @-menu ingame.
Example of @-menu with 40-points column width
> Several tweaks to player info menu

- src/overmap.cpp
Balance "Wandering Hordes prefer to wander and recruit in open terrain"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/65561 by @stubkan.
> Wandering Hordes prefer to wander and recruit in open terrain

- .github/workflows/release.yml
- android/app/build.gradle
None
We can support Android build in this way for the time being.  As for the so-called security, I don't think it's a special consideration for the project right now, let alone that we don't plan to put it on the app store so we can think about it later.  It is from  andrei8l           https://github.com/andrei8l/Cataclysm-DDA/commit/e5b43223b156c06b160d1184407810fb32fc2cd4.   You can skip all the tests and merge it because it doesn't have any c++ code and json code. Existing tests don't make sense for this PR either.
If you're not giving up on your project, get up and approve the workflow 👿.This PR  I  used the master branch directly, and after this PR, I will work with other branches normally.@Night-Pryanik
> build Android version  part-01

- src/character_modifier.cpp
None
I think many of SurFlurer's optimized PR are very valuable, and for safety reasons, we rely on DDA's recognition of PR.
His other two are PR for caching workbench multipliers and caching character radiation levels. I think they can be merged, and those implementation has already been merged on my toy project.
> Cache a flag in Character::get_limb_score()  ------ from SurFlurer

- data/json/overmap/map_extras.json
- data/json/overmap/overmap_connections.json
- data/json/overmap/overmap_terrain/overmap_terrain_transportation.json
- data/json/regional_map_settings.json
- src/map_extras.cpp
- src/mapgen_functions.cpp
- src/overmap.cpp
- src/overmapbuffer.cpp
Content "Fungal infestation map extra"
Add some fungal fun to cities.
- Added a special `city_center` OMT which can be assigned as a place for guaranteed spawn of map extras inside city borders.
- Added fungal infestation map extra. 5% chance to spawn in every city. It will spawn only if there's at least one park found in the city (the list of parks is defined in regional settings). It will search for suitable location (grass, dirt, sand etc) inside one of the parks and if search is successful, it will spawn fungal spire on suitable tile and 1..3 fungaloids around.
None.
Debug-spawned map extra in a city with a park. Checked that fungal spire and fungaloids are correctly spawned on random suitable location.
Also teleported around the world and searched for map extra to spawn naturally. …
> Fungal infestation map extra

- data/changelog.txt
- data/json/overmap/map_extras.json
- data/json/regional_map_settings.json
- src/map_extras.cpp
- src/regional_settings.h
Content "Barricaded house map extra"
Add more life to cities.
Added new map extra which can spawn only in cities. 5% chance per city.
Map extra will board up all windows and doors in the house, barricade most windows and doors with some kind of furniture, and spawn either a zombie or a human survivor inside.
None.
Debug-spawned map extra dozens of times.
> Barricaded house map extra

- src/character_escape.cpp
- src/monattack.cpp
Interface "More cases for not logging monster attacks or NPCs trying to break free from various traps and debilitating effects"
Cover more cases.
New options for showing (not showing) messages when:
- NPCs trying to break free from various debilitating effects and traps;
- monsters performing grab, ranged pull, and grab-and-drag attacks.
None.
Spawned zombie wrestler and NPC. Watched wrestler performed several types of attacks on NPC, watched NPC stood down after the hit. Also just in case let wrestler perform its attacks on me to check whether messages are still being shown.
None.
> More cases for not logging monster attacks or NPCs trying to break free from various traps and debilitating effects

- data/core/game_balance.json
- src/options.cpp
None
Make it more convenient for players to adjust options.
Moved from external options to game options.
None.
> Moved animals spawn rate settings from external options to game options
