src/melee.cpp
All work is done by @Demivan in #54439.
=> Made melee weapons only wear down when hit is successful

src/cached_options.cpp, src/cached_options.h, src/descriptions.cpp, src/item.cpp, src/monster.cpp, src/options.cpp
Based on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1875 and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2036 by @kheirferrum.
=> Added interface option to display (or not) source of content when examining an item

src/game.cpp, src/options.cpp
Features "Prompt player to return to main menu on character death"
=> Prompt player to return to main menu on character death

data/json/furniture_and_terrain/terrain-floors-indoor.json
Features "Utility light no longer emits light by itself, intead it can be converted into a standing floodlight appliance"
=> Utility light no longer emits light by itself, intead it can be converted into a standing floodlight appliance

data/changelog.txt, src/character.cpp
Inerface "Show gender on NPC"
Ported from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/823 by @Firestorm01X2.
=> Show gender on NPC

.github/workflows/msvc-full-features.yml, data/json/furniture_and_terrain/terrain-floors-indoor.json
=> Trying to make build work

.github/workflows/release.yml
=> Changed name from CDDA to TISH

data/mods/No_Hope/monsters.json, data/mods/No_Hope/recipes.json
Mods "Fixed inability to disassemble laser turret in No Hope mod"
=> Fixed inability to disassemble laser turret in No Hope mod

.github/workflows/release.yml
Reverts Cataclysm-TISH-team/Cataclysm-TISH#13
=> Revert "Changed name from CDDA to TISH"

.github/workflows/release.yml
Reverts Cataclysm-TISH-team/Cataclysm-TISH#20
=> Revert "Revert "Changed name from CDDA to TISH""

src/inventory_ui.cpp
None
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/64632 by @katemonster33.
=> Mouse hover in inventory

src/npcmove.cpp
None
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/64822 by @SurFlurer.
=> NPC complain about theft

src/player_display.cpp
Category "Brief description"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64819 by @katemonster33.
=> Mouse hover in @ menu

src/magic.cpp
Bugfixes "Fix spell copy-from"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64839 by @Ramza13.
=> Fix spell copy-from

.github/workflows/CBA.yml, .github/workflows/check-translation.yml, .github/workflows/clang-tidy.yml, .github/workflows/cmake-format.yml, .github/workflows/codeql-analysis.yml, .github/workflows/comment-commands.yml, .github/workflows/flake8.yml, .github/workflows/labeler.yml, .github/workflows/matrix.yml, .github/workflows/msvc-full-features.yml, .github/workflows/push-translation-template.yml, .github/workflows/release.yml, .github/workflows/summary-labeler.yml, .github/workflows/text-changes-analyzer.yml, .github/workflows/toc.yml
None
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/64920 by @casswedson.
=> Updated action/checkout versions

.github/workflows/CBA.yml, .github/workflows/astyle.yml, .github/workflows/json.yml, .github/workflows/matrix.yml, .github/workflows/release.yml, .github/workflows/text-changes-analyzer.yml, data/json/items/armor/bespoke_armor/custom_bodysuits.json, data/json/items/armor/bespoke_armor/custom_storage.json, data/json/items/armor/suits_protection.json, data/json/items/comestibles/drink_other.json, data/json/recipes/food/casseroles.json, src/item.cpp
=> Routine CDDA merge

data/title/en.alt1, data/title/en.title, src/main_menu.cpp
=> Changed ASCII art from CDDA to TISH

src/game.cpp, src/player_activity.cpp
Features "Auto-move now takes distraction manager into account"
Ported https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2664 by @chaosvolt.
=> Auto-move uses distraction manager

data/json/mutations/mutations.json, src/iuse_actor.cpp
None
Hinted by @chaosvolt in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2681.
=> Allowed manual installing non-sterile CBMs with Infection Immune trait

src/veh_interact.cpp, src/vehicle.cpp, src/vehicle.h
Interface "Display why vehicle parts cannot be installed"
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/65341 and https://github.com/CleverRaven/Cataclysm-DDA/pull/65472 by @RenechCDDA.
=> Display why vehicle parts cannot be installed

android/app/build.gradle
None
After the previous installation, the apk name was still "Cataclysm DDA", and I made modifications. At the same time, I changed the package name, which can now coexist with CDDA.
=> Fix apk version ，name，package name

data/changelog.txt, src/options.cpp
None
Compact and more readable options menu.
Added several new options groups.
=> Added more options group
